In [36]:
import pandas as pd

In [37]:
data = pd.read_csv('data/student-por.csv', sep=';')

In [38]:
data.drop(['G1', 'G2', 'Fjob', 'Mjob', 'reason'], axis=1)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,guardian,traveltime,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G3
0,GP,F,18,U,GT3,A,4,4,mother,2,...,no,no,4,3,4,1,1,3,4,11
1,GP,F,17,U,GT3,T,1,1,father,1,...,yes,no,5,3,3,1,1,3,2,11
2,GP,F,15,U,LE3,T,1,1,mother,1,...,yes,no,4,3,2,2,3,3,6,12
3,GP,F,15,U,GT3,T,4,2,mother,1,...,yes,yes,3,2,2,1,1,5,0,14
4,GP,F,16,U,GT3,T,3,3,father,1,...,no,no,4,3,2,1,2,5,0,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,MS,F,19,R,GT3,T,2,3,mother,1,...,yes,no,5,4,2,1,2,5,4,10
645,MS,F,18,U,LE3,T,3,1,mother,1,...,yes,no,4,3,4,1,1,1,4,16
646,MS,F,18,U,GT3,T,1,1,mother,2,...,no,no,1,1,1,1,1,5,6,9
647,MS,M,17,U,LE3,T,3,1,mother,2,...,yes,no,2,4,5,3,4,2,6,10
648,MS,M,18,R,LE3,T,3,2,mother,3,...,yes,no,4,4,1,3,4,5,4,11

Convert the numeric data into categorical data. Transform the following columnsâ€™ numeric data into categorical data according to the bounds specified below:

    age
        age < 18: "low"
        age >= 18: "high"

    failures
        failures < 2: "low"
        failures >= 2: "high"

    absences
        absences < 2: "low"
        2 <= absences < 10: "medium"
        10 <= absences: "high"

    G3
        G < 10: "fail"
        G >= 10: "pass"

    famrel, freetime, goout, Dalc, Walc, Medu, Fedu, studytime, health: these all have 5 levels, but we can simplify to 2
        < 3: "low"
        >= 3: "high"

In [39]:
cleaned = data.where(data['age'] < 18, 'low').where(data['age'] >= 18, 'high')

In [40]:
cleaned = data.where(data['failures'] < 2, 'low').where(data['failures'] >= 2, 'high')

In [41]:
cleaned = data.where(data['absences'] < 2, 'low').where(data['failures'].between(2, 10, inclusive='left'), 'medium').where(data['absences'] >= 10, 'high')

In [44]:
cleaned = data.where(data['G3'] < 3, 'low').where(data['G3'] >= 3, 'high')

In [45]:
def transform_por_data(filepath):

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,low,low,low,low,low,low,low,low,low,low,...,low,low,low,low,low,low,low,low,low,low
1,low,low,low,low,low,low,low,low,low,low,...,low,low,low,low,low,low,low,low,low,low
2,low,low,low,low,low,low,low,low,low,low,...,low,low,low,low,low,low,low,low,low,low
3,low,low,low,low,low,low,low,low,low,low,...,low,low,low,low,low,low,low,low,low,low
4,low,low,low,low,low,low,low,low,low,low,...,low,low,low,low,low,low,low,low,low,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,low,low,low,low,low,low,low,low,low,low,...,low,low,low,low,low,low,low,low,low,low
645,low,low,low,low,low,low,low,low,low,low,...,low,low,low,low,low,low,low,low,low,low
646,low,low,low,low,low,low,low,low,low,low,...,low,low,low,low,low,low,low,low,low,low
647,low,low,low,low,low,low,low,low,low,low,...,low,low,low,low,low,low,low,low,low,low
648,low,low,low,low,low,low,low,low,low,low,...,low,low,low,low,low,low,low,low,low,low